### ISSUE TITLE
Same roi_select area on different comparions/images

### ISSUE THREAD

**Issue by apelin20** [ropensci/colocr#8]
Hello,

Very useful and unique package. I am comparing multiple markers against one and was wondering if I could somehow use the same roi_select coordinates on a few different images to perform the tests on the same area in each case?

Alternatively, is it possible to perform the test without roi_select (i.e. on the whole image)?

Thanks!

**Comment by MahShaaban** [comment]
- Please check this section of the vignette https://docs.ropensci.org/colocr/articles/using_colocr.html#analyzing-a-collection-of-images-at-once

**Comment by apelin20** [comment]
Thank you! I am having difficulty analyzing the 2 images:

```
> fls <- c("test1.png", "test3.png")
> image_list <- image_load(fls)
> image_list %>% roi_select(threshold = 90) %>% roi_test()
Error in `[.default`(im, , , , ind, drop = FALSE) : 
  subscript out of bounds
In addition: Warning messages:
1: In grayscale(img) : Image appears to already be in grayscale mode
2: In grayscale(img) : Image appears to already be in grayscale mode
3: In grayscale(img) : Image appears to already be in grayscale mode
```

The issue is likely the fact that I had to process the images in magick and needed to convert them to grayscale. Is it still possible to compare the pixel intensities?

One more question, is it possible to do roi_select once on imgRef and use that when coomparing img1 to img2, 1 to 3, etc...

**Comment by MahShaaban** [comment]
- I am not sure what to do in that case. You could try to replicate the processing in `colocr`
- I assume you can. Can you give an example?
